// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "../todo/Todo.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as TodoItem from "../todo-item/TodoItem.bs.js";

var defaultState_todos = [];

var defaultState = {
  todos: defaultState_todos,
  input: ""
};

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            todos: state.todos.concat([{
                    TAG: /* Incomplete */1,
                    content: state.input
                  }]),
            input: ""
          };
  }
  switch (action.TAG | 0) {
    case /* Remove */0 :
        var id = action.id;
        return {
                todos: state.todos.filter(function (param, i) {
                      return i !== id;
                    }),
                input: state.input
              };
    case /* Toggle */1 :
        var id$1 = action.id;
        return {
                todos: state.todos.map(function (todo, i) {
                      if (id$1 === i) {
                        return Todo.toggle({
                                    TAG: /* A */2,
                                    _0: 1
                                  });
                      } else {
                        return todo;
                      }
                    }),
                input: state.input
              };
    case /* InputChange */2 :
        return {
                todos: state.todos,
                input: action.value
              };
    
  }
}

function List(Props) {
  var match = React.useReducer(reducer, defaultState);
  var dispatch = match[1];
  var match$1 = match[0];
  var todos = match$1.todos;
  var onChange = function ($$event) {
    var value = $$event.target.value;
    return Curry._1(dispatch, {
                TAG: /* InputChange */2,
                value: value
              });
  };
  var handleDispatch = function (param) {
    return Curry._1(dispatch, /* Add */0);
  };
  var onKeyPress = function ($$event) {
    if ($$event.key === "Enter") {
      return Curry._1(dispatch, /* Add */0);
    }
    
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement("input", {
                      value: match$1.input,
                      onKeyPress: onKeyPress,
                      onChange: onChange
                    }), React.createElement("button", {
                      onClick: handleDispatch
                    }, "Add")), todos.length === 0 ? React.createElement("p", undefined, "You haven't added anything to your list yet.") : React.createElement("ol", undefined, todos.map(function (todo, i) {
                        return React.createElement(TodoItem.make, {
                                    onToggle: (function (param) {
                                        return Curry._1(dispatch, {
                                                    TAG: /* Toggle */1,
                                                    id: i
                                                  });
                                      }),
                                    todo: todo,
                                    key: i.toString()
                                  });
                      })));
}

var make = List;

export {
  defaultState ,
  reducer ,
  make ,
  
}
/* react Not a pure module */
