// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Item from "../item/Item.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "./State.bs.js";
import * as React from "react";

function List(Props) {
  var match = React.useReducer(State.reducer, State.defaultState);
  var state = match[0];
  var todos = state.todos;
  var dispatch = match[1];
  var onChange = function ($$event) {
    var value = $$event.target.value;
    return Curry._1(dispatch, {
                TAG: /* InputChange */1,
                value: value
              });
  };
  var handleDispatch = function (param) {
    return Curry._1(dispatch, /* Add */0);
  };
  var onKeyPress = function ($$event) {
    if ($$event.key === "Enter") {
      return Curry._1(dispatch, /* Add */0);
    }
    
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement("input", {
                      value: state.input,
                      onKeyPress: onKeyPress,
                      onChange: onChange
                    }), React.createElement("button", {
                      onClick: handleDispatch
                    }, "Add")), todos.length === 0 ? React.createElement("p", undefined, "You haven't added anything to your list yet.") : React.createElement("ol", undefined, todos.map(function (todo, i) {
                        return React.createElement(Item.make, {
                                    todo: todo,
                                    key: i.toString()
                                  });
                      })));
}

var make = List;

export {
  make ,
  
}
/* Item Not a pure module */
