// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Item from "../item/Item.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var defaultState_todos = [];

var defaultState = {
  todos: defaultState_todos,
  input: ""
};

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            todos: state.todos.concat([{
                    content: state.input
                  }]),
            input: ""
          };
  }
  if (action.TAG !== /* Remove */0) {
    return {
            todos: state.todos,
            input: action.value
          };
  }
  var id = action.id;
  return {
          todos: state.todos.filter(function (param, i) {
                return i !== id;
              }),
          input: state.input
        };
}

function List(Props) {
  var match = React.useReducer(reducer, defaultState);
  var dispatch = match[1];
  var match$1 = match[0];
  var todos = match$1.todos;
  var onChange = function ($$event) {
    var value = $$event.target.value;
    return Curry._1(dispatch, {
                TAG: /* InputChange */1,
                value: value
              });
  };
  var handleDispatch = function (param) {
    return Curry._1(dispatch, /* Add */0);
  };
  var onKeyPress = function ($$event) {
    if ($$event.key === "Enter") {
      return Curry._1(dispatch, /* Add */0);
    }
    
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement("input", {
                      value: match$1.input,
                      onKeyPress: onKeyPress,
                      onChange: onChange
                    }), React.createElement("button", {
                      onClick: handleDispatch
                    }, "Add")), todos.length === 0 ? React.createElement("p", undefined, "You haven't added anything to your list yet.") : React.createElement("ol", undefined, todos.map(function (todo, i) {
                        return React.createElement(Item.make, {
                                    todo: todo,
                                    key: i.toString()
                                  });
                      })));
}

var make = List;

export {
  defaultState ,
  reducer ,
  make ,
  
}
/* Item Not a pure module */
