// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TodoList from "../todo-list/TodoList.bs.js";
import * as Core from "@material-ui/core";

function App(Props) {
  return React.createElement(Core.Grid, {
              alignContent: "center",
              children: React.createElement(Core.Grid, {
                    children: React.createElement(Core.Card, {
                          children: React.createElement(Core.CardContent, {
                                children: React.createElement(TodoList.make, {})
                              })
                        }),
                    item: true
                  }),
              container: true,
              justify: "center",
              style: {
                backgroundColor: "#cfe8fc",
                height: "100vh"
              }
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
