// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TodoList from "../todo-list/TodoList.bs.js";
import * as Core from "@material-ui/core";

function App(Props) {
  return React.createElement(Core.Container, {
              children: React.createElement(TodoList.make, {})
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
