// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as UseToggle from "../../core/use-toggle/UseToggle.bs.js";
import * as IndexModuleScss from "./index.module.scss";

var styles = IndexModuleScss;

function Item(Props) {
  var todo = Props.todo;
  var match = UseToggle.useToggle(undefined, undefined);
  var toggle = match[1];
  var handleButtonClick = function (param) {
    return Curry._1(toggle, undefined);
  };
  return React.createElement("li", {
              className: styles.item
            }, match[0] ? React.createElement("div", undefined, React.createElement("input", {
                        readOnly: true,
                        value: todo.content
                      }), React.createElement("button", {
                        onClick: handleButtonClick
                      }, "Update")) : React.createElement("div", {
                    onClick: (function (param) {
                        return Curry._1(toggle, undefined);
                      })
                  }, todo.content));
}

var make = Item;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
