// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as UseToggle from "../use-toggle/UseToggle.bs.js";

function TodoItem(Props) {
  var todo = Props.todo;
  var match = UseToggle.useToggle(undefined, undefined);
  var toggle = match[1];
  var handleButtonClick = function (param) {
    return Curry._1(toggle, undefined);
  };
  return React.createElement("li", undefined, match[0] ? React.createElement("div", undefined, React.createElement("input", {
                        readOnly: true,
                        value: todo.content
                      }), React.createElement("button", {
                        onClick: handleButtonClick
                      }, "Update")) : React.createElement("div", {
                    onClick: (function (param) {
                        return Curry._1(toggle, undefined);
                      })
                  }, todo.content));
}

var make = TodoItem;

export {
  make ,
  
}
/* react Not a pure module */
