// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "rescript/lib/es6/caml_array.js";

var defaultState_todos = [];

var defaultState = {
  todos: defaultState_todos,
  input: ""
};

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            todos: state.todos.concat([{
                    content: state.input
                  }]),
            input: ""
          };
  }
  switch (action.TAG | 0) {
    case /* Remove */0 :
        var i = action._0;
        return {
                todos: state.todos.filter(function (param, index) {
                      return index !== i;
                    }),
                input: state.input
              };
    case /* InputChange */1 :
        return {
                todos: state.todos,
                input: action._0
              };
    case /* Update */2 :
        var i$1 = action.i;
        var index = state.todos.findIndex(function (param, index) {
              return index === i$1;
            });
        if (index > -1) {
          Caml_array.get(state.todos, index).content = action.value;
        }
        return state;
    
  }
}

export {
  defaultState ,
  reducer ,
  
}
/* No side effect */
