// Generated by ReScript, PLEASE EDIT WITH CARE


var Add = {};

var Edit = {};

var Delete = {};

var Check = {};

var Cancel = {};

export {
  Add ,
  Edit ,
  Delete ,
  Check ,
  Cancel ,
  
}
/* No side effect */
